name: bodysync
description: A fitness tracking app built with Flutter and Firebase.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.1.0

  # Google Sign-in
  google_sign_in: ^6.2.1

  # State Management
  flutter_riverpod: ^2.5.1

  # Utils
  intl: ^0.19.0

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
